### PR TITLE
Add project logo

### PR DESCRIPTION
**Pull request by buttercrab**
This revision includes:
- Add project logo based on [comment](https://github.com/utilForever/InfinityMetro/pull/18#issuecomment-704942389)

**Preview:**

### CODE REVIEW

**Comment by utilForever** [comment]
What do you think this logo? I prefer it.
metro

**Comment by buttercrab** [comment]
I'll make the logo based on your logo.

**Comment by jshyunbin** [comment]
good

**Comment by buttercrab** [comment]
@utilForever @jshyunbin How about changed logo?

**Comment by utilForever** [comment]
@buttercrab Good. 👍

**Review by utilForever — APPROVED** [review]
LGTM. Please insert PR description.

**Comment by buttercrab** [comment]
@utilForever Added preview to description.

**Comment by utilForever** [comment]
@buttercrab Good to go.

**Pull request merged**
